### ISSUE TITLE
Installation loads Roassal2 and Roassal3

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#116]
With [Roassal3 released](https://github.com/ObjectProfile/Roassal3) it could represent a great amount of duplication to have both versions loaded in the same image.

Most Roassal2 class dependencies I've found are in Cormas-UI (only 3 dependencies in Cormas-Core) and they are:

- RTGrapher
- RTGhostDraggable
- RTZoomInMove
- RTZoomOutMove
- RTData
- RTBox
- RTEllipse
- RTGridLayout
- RTActiveAnimation
- RTMenuBuilder
- RTHTML5Exporter
- RTSVGExporter
- RTPNGExporter
- RTViewForSpec

**Comment by nbecu** [comment]
I had a look at Roassal3 and it seems great. 
Knowing that Roassal dev team will no longer work on Roassal2,  it should be a good thing to migrate to Roassal3. 

Yet it's not clear to me how Roassal3 can be plugged with script. How can you have Roassal 3 canvas and a Script menu in a same window?

More over it seems a quite large of work to migrate to Roassal3. Personally for the time being i don't have time to work on Cormas dev. Sorry. 😞

So if someone does the migration I think it would be cool, but I won't be able to help. 

Cheers

**Comment by SergeStinckwich** [comment]
hi @hernanmd in fact this is not a mistake, but the idea was to migrate progressively the visualisation from Roassal 2 to Roassal 3. This is why at the moment, the baseline loads the two. Later we will remove the dependency to Roassal2.

**Comment by hernanmd** [comment]
Ok Serge, I think I could take another issue for now and then we could leave this one opened.

**Comment by akevalion** [comment]
Let me know if I can help with the global issue I have more time in home then I can pair programming and port it to Roassal3

**Comment by SergeStinckwich** [comment]
That would be great ! what is prefered time? I'm GMT+8

**Comment by akevalion** [comment]
@SergeStinckwich from 14:00 to: 17:00, Santiago time GMT -4

**Comment by SergeStinckwich** [comment]
I'm in Macau: we have 12 hours difference: https://www.timeanddate.com/worldclock/meetingtime.html?iso=20200529&p1=754&p2=232

2pm to 5pm for you is 2am to 5am for me 👎 
We can try something at 8am/8pm.

Would be easier for people in Europe.

**Comment by akevalion** [comment]
Lets have a meeting Friday 22:00 in Santiago, Macau: 10:00.

**Comment by SergeStinckwich** [comment]
Which Friday? now?
