### ISSUE TITLE
selectCellsInRectangle: has strange coordinates

### ISSUE THREAD

**Issue by tomooda** [cormas/cormas#124]
``CormasModel>>selectCellsInRectangle:`` takes aRectangle as an argument whose x coordinate means line and y coordinate means column.
This is odd comparing to the definition of ``CMSpatialEntityElement>>x`` and ``CMSpatialEntityElement>>y`` that return column number and line number in order.

**Comment by SergeStinckwich** [comment]
Actually this method is never called ... This is one of the numerous method, that we don't know if they are used in any models.

**Comment by tomooda** [comment]
Yes, that's the problem. Can I mark this method as obsolete and create a new API with a slightly different name?

**Comment by SergeStinckwich** [comment]
We should ask @pierbo if this method is used in models that we don't know. I see you add a test for this method, this is nice.

**Comment by tomooda** [comment]
Yes, the current test does not distinguish x and y so it should work in either way. :-)

**Comment by SergeStinckwich** [comment]
Decision from the meeting: rename selectCells* methods in CormasModel as cells* methods and mark them as obsolete.

**Comment by tomooda** [comment]
related topic: https://github.com/cormas/cormas/issues/129

**Comment by SergeStinckwich** [comment]
I reopen. We have to rename the methods before closing this issue.

**Comment by SergeStinckwich** [comment]
Can we close this one?

**Comment by tomooda** [comment]
I think we've done this already.
