### ISSUE TITLE
x and y in method names should be column and line

### ISSUE THREAD

**Issue by tomooda** [cormas/cormas#129]
In some code, x means column and y means line, and in some other code, the other way around.
To avoid confusion, we better use literally line and column.
To keep compatibility with the existing API, we keep them but just mark "obsolete" and create new APIs.

**Comment by tomooda** [comment]
https://github.com/cormas/cormas/pull/130

**Comment by ElCep** [comment]
Maybe we can decide on an order in the next functionalities.
As I'm an [R](https://www.r-project.org/) user I would like to have the rows first and the columns second when you use both. What do yo think ?

**Comment by SergeStinckwich** [comment]
> Maybe we can decide on an order in the next functionalities.
> As I'm an [R](https://www.r-project.org/) user I would like to have the rows first and the columns second when you use both. What do yo think ?

Not sure to understand. If we name them lines and columns, no order is needed?

**Comment by ElCep** [comment]
It's true but as a convention, in the new api we can say that we ask for the row first and the column second ?

**Comment by tomooda** [comment]
line and column, to say precisely. I found 3 methods that has line:column: in its name.
* CMSpaceModel>>line:column:
* CMSpaceModel>>line:column:shape:nbNeighbours:boundaries:
* MenuSpaceInterfaces>>initGridSizeLine:column:
So, I agree with @ElCep. It seems createGridLines:columns:... would be coherent to other parts of Cormas.
I'll make a PR for this.

**Comment by SergeStinckwich** [comment]
Thank you @tomooda I integrate the PR. Can we close this issue?
