### ISSUE TITLE
Remove passmode methods

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#13]
There is several methods passMode in various classes : CormasEntity, CormasModel, EntityPOV, ... I guess they are related to serialisation and openTalk. Can we remove them ?

**Comment by nbecu** [comment]
Hi
The passMode is related to the distributed mode of Cormas which uses Opentalk StToSt library.
As we decided not to integrate the distribution mode in the pahro version for the mmoment, then , Yes, wen can remove those methods

**Comment by SergeStinckwich** [comment]
ok done in Cormas-Core-SergeStinckwich.101
