### ISSUE TITLE
What is ASC file?

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#135]
In ``CMSpaceModel`` there is a ``getDataFromASCFile: aFileName``.

What is an ASC file ? what is the purpose?

**Comment by ChLePage** [comment]
This is Esri ASCII raster format, used to transfer information to or from other cell-based or raster systems. The file begin with header information that defines the properties of the raster such as the cell size, the number of rows and columns, and the coordinates of the origin of the raster. The header information is followed by cell value information specified in space-delimited row-major order, with each row separated by a carriage return. Example ASCII raster:
ncols 480
nrows 450
xllcorner 378923
yllcorner 4072345
cellsize 30
nodata_value -32768
43 2 45 7 3 56 2 5 23 65 34 6 32 54 57 34 2 2 54 6 
35 45 65 34 2 6 78 4 2 6 89 3 2 7 45 23 5 8 4 1 62 ...

**Comment by pierbo** [comment]
I think this kind of procedures will be changed in Cormas-Pharo in order to be compliant with Roassal and the way to load vectorial or raster maps.

**Comment by ElCep** [comment]
I guess, it's a GIS file formated as a matrix of attribut e.g. https://en.wikipedia.org/wiki/Esri_grid

**Comment by SergeStinckwich** [comment]
There is already some ESRI support in Pharo done by @hernanmd here: https://github.com/hernanmd/Shapes

**Comment by SergeStinckwich** [comment]
Do we want to continue supporting ESRI in future version of CORMAS?
What is the scenario of using ESRI in CORMAS?

**Comment by SergeStinckwich** [comment]
> I think this kind of procedures will be changed in Cormas-Pharo in order to be compliant with Roassal and the way to load vectorial or raster maps.

Pierre, I don't see the relationship to Roassal.

**Comment by ElCep** [comment]
> Do we want to continue supporting ESRI in future version of CORMAS?
> What is the scenario of using ESRI in CORMAS?

The fact is that is not strictly speaking an ESRI format. It is an open format proposed by ESRI. It has become a standard form of exchange for giving GIS. E.g. [wikipedia](https://en.wikipedia.org/wiki/Esri_grid) "A non-proprietary ASCII format, also known as an ARC/INFO ASCII GRID"
To answer your question @SergeStinckwich , yes, we should keep this thing.

**Comment by pierbo** [comment]
Well, I thought that Roassal already had procedures for loading maps... but I sow that Hernan did it !
Regarding the question about ESRI, I don't know as I never used such GIS platform, but perhaps some modelers use it (?)

**Comment by ElCep** [comment]
Modellers who come from geography for sure!

**Comment by SergeStinckwich** [comment]
> Well, I thought that Roassal already had procedures for loading maps... but I sow that Hernan did it !
> Regarding the question about ESRI, I don't know as I never used such GIS platform, but perhaps some modelers use it (?)

Someone use Roassal to load OpenStreetMap and shapefiles.

**Comment by SergeStinckwich** [comment]
> Modellers who come from geography for sure!

Do we have one example of using ESRI that is used in one CORMAS model, so I can add it as a kind of test?

@hernanmd can you put your code on github?

**Comment by SergeStinckwich** [comment]
There was a special tool to load ESRI file and use them as space for models?

**Comment by SergeStinckwich** [comment]
Apparently @hernanmd Shapes does not support raster file, only vectorial.

**Comment by SergeStinckwich** [comment]
We are more looking for something like: ESRI ASCII raster format
http://help.arcgis.com/en/arcgisdesktop/10.0/help/index.html#/ESRI_ASCII_raster_format/009t0000000z000000/

**Comment by SergeStinckwich** [comment]
Example: https://github.com/dice-cyfronet/ascii-grid-source/blob/master/src/test/resources/topography.txt

**Comment by nbecu** [comment]
Hi

Can you provide a link to " @hernanmd <https://github.com/hernanmd> Shapes".
It would be interesting to see in the future how we could integrate shape
files uploading for Corma

Le mar. 2 juin 2020 à 11:55, Serge Stinckwich <notifications@github.com> a
écrit :

**Comment by nbecu** [comment]
Yes, that is the type of format that corresponds to what is called  ASC
file in Cormas.   Btw, in would be good to rename this asc file into
"raster ascii" file

Le mar. 2 juin 2020 à 12:13, Serge Stinckwich <notifications@github.com> a
écrit :

**Comment by SergeStinckwich** [comment]
> Hi Can you provide a link to " @hernanmd <https://github.com/hernanmd> Shapes". It would be interesting to see in the future how we could integrate shape files uploading for Cormas

I already give the link, this is: http://smalltalkhub.com/#!/~hernan/Shapes
but there is no support for ESRI raster ascii.

**Comment by hernanmd** [comment]
I can update the project (I'm not clear if the support of Shapes is enough for Cormas yet).
However I've seen that there people which [actively asks for remove the ESRI support](http://switchfromshapefile.org/) from OSS projects.

are newer projects like GeoJSON (only compatible with WGS84 projection) and [TopoJSON](https://en.wikipedia.org/wiki/GeoJSON#TopoJSON) which could be interesting and more up to date with the current developments outside the Smalltalk arena.

So if the idea is to support several GIS systems we could start very small thinking about proper integration (see this paper about [Reference Systems](https://hillside.net/plop/plop97/Proceedings/balaguer_gordillo_dasneves.pdf) and [this one](https://dl.acm.org/doi/pdf/10.1145/288692.288707) for example). I know Federico and I could ask him about this.

I would build a CORMAS-MiniGIS and then add wrappers/bindings to different formats from there

CORMAS-MiniGIS-ESRI
CORMAS-MiniGIS-GeoJSON
CORMAS-MiniGIS-TopoJSON
...

What do you think?

**Comment by SergeStinckwich** [comment]
Stéphane implement a version: https://github.com/Ducasse/ESRI-ASCII-Raster

**Comment by SergeStinckwich** [comment]
> I can update the project (I'm not clear if the support of Shapes is enough for Cormas yet).
> However I've seen that there people which [actively asks for remove the ESRI support](http://switchfromshapefile.org/) from OSS projects.
> 
> And there are newer projects like [GeoJSON](https://github.com/noha/geo-json) (only compatible with WGS84 projection) and [TopoJSON](https://en.wikipedia.org/wiki/GeoJSON#TopoJSON) which could be interesting and more up to date with the current developments outside the Smalltalk arena.
> 
> So if the idea is to support several GIS systems we could start very small thinking about proper integration (see this paper about [Reference Systems](https://hillside.net/plop/plop97/Proceedings/balaguer_gordillo_dasneves.pdf) and [this one](https://dl.acm.org/doi/pdf/10.1145/288692.288707) for example). I know Federico and I could ask him about this.
> 
> I would build a CORMAS-MiniGIS and then add wrappers/bindings to different formats from there
> 
> CORMAS-MiniGIS-ESRI
> CORMAS-MiniGIS-GeoJSON
> CORMAS-MiniGIS-TopoJSON
> ...
> 
> What do you think?

I guess @ElCep will be interested to have GeoJSON and ESRI and more elaborate stuff like the one describe here: #139 

Interesting work of Federico. He is still working on that? His code is not available?

**Comment by ElCep** [comment]
Yeah, it'd be really cool to collect GIS tools bit by bit. Great idea and @hernanmd 's proposal to start with wrapper! 
Maybe to keep the Open Geospatial Consorsum standard set in a head corner. For exemple there is some spec for [geoJSON](https://www.ogc.org/standards/eo-geojson) or [GeoPackage](https://www.ogc.org/standards/geopackage) (the new generation of GIS files... in 20 years will be shp killer :sun_behind_large_cloud: ). By the way, [WKT](https://www.ogc.org/standards/wkt-crs) can be a easy way to deal with GIS. It can be copy/past directly from Qgis.
