### ISSUE TITLE
Create a CMEnvFileReader for space model

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#141]
The #loadEnvironmentFile: method contains logic for parsing a .env file, which handles several cases through if sentences.
We could move these load environment methods to a separate class to:

  - Clean CMSpaceModel
  - Facilitate testing and enhacements to the parser
  - To have a separate reader which could be later replaced as needed.

**Comment by SergeStinckwich** [comment]
I agree with that :-)

**Comment by SergeStinckwich** [comment]
Hernan, did you made some progress on this one, because I see you have done a branch on this issue?

**Comment by hernanmd** [comment]
Hi Serge, I just did a push. It took me a long time pairing each debugging step with the VW version.

What I did is to split a lot of methods, specially related with the .env parsing, into CMEnvFileReader and CMEnvFile. I think it is a bit simplified now. The CMEnvFile represents an object built as result of reading the .env file, and also stores the CSV "matrix" (= .env file contents) as a way to reduce the parameter passing in a lot of messages. The entry point of this PR is the method #loadEnvironmentFromFile:

Some stuff (idiom maybe) I don't know if they are necessary to port, for example in the VW version the matrix (actually an OrderedCollection now) elements are removed while parsing its contents. I prefered to discard its elements #allButFirst: ... where needed. Also there are events triggered which need to be revised because we could use ValueHolders although this is a "minor" issue.

More work is needed but I think it will be safer to open another issue to integrate the .env reading results into Space model , because now CMSpaceModel is too complex: For example I couldn't found a space model where #isFull evaluates to false, but in the Pharo version always evaluated to true, using my example method.

**Comment by SergeStinckwich** [comment]
@tomooda add support fort .cells files instead of using .env files, so I guess this issue can be closed. @hernanmd are you ok with that?

**Comment by tomooda** [comment]
Hernan's refactoring effort to separate the .env file reader from the space model was a very important step to implement the cells file reader. Great thanks to @hernanmd  to improve the code.

**Comment by hernanmd** [comment]
Hi @SergeStinckwich and @tomooda yes please, if the code is not useful feel free to close the issue and/or modify it. 

I will be able to contribute to codebase once I finish administrative paperwork here.
