### ISSUE TITLE
Human readable model names versus CM"ModelName"Model

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#150]
We have a particular method to "resolve" a model class name to its folder name (which contains model resources), i.e. to go from ``CMConwayModel`` to Conway:

This method is #stringToFilename:

Now in the ``CMEnvFileReader`` I wrote this:

```smalltalk
stringToFilename: aStringOrFilename
	"Returns a <FileReference> from (aStringOrFilename) located into the current model 'maps' 
	directory (ex: 'cormas.env') "

	| aFilename modelFolderName |
	aStringOrFilename isString
		ifTrue: [ 
			modelFolderName := self resolveModelName: aStringOrFilename.
			aFilename := (self resourceLocator mapsPath: modelFolderName) / aStringOrFilename ]
		ifFalse: [ aFilename := aStringOrFilename asFileReference ].
	^ aFilename
```

which delegates this problem to #resolveModelName:

```smalltalk
resolveModelName: aStringOrFilename
	"Very bad hack to remove CM and Model to a model name ..."
	
	| modelFolderName |
	self flag: #shouldBeRevised.
	modelFolderName := self cormasModelClass name.
	(modelFolderName beginsWith: 'CM')
		ifTrue: [ modelFolderName := modelFolderName allButFirst: 2 ].
	(modelFolderName endsWith: 'Model')
		ifTrue: [ modelFolderName := modelFolderName allButLast: 5 ].
	^ modelFolderName
````

What should we do about this?
Any ideas are welcome.

**Comment by tomooda** [comment]
I'd prefer delegating it to the model class, and the model class answers like the below by default.

```
CormasModel class>>modelFolderName
        "My subclasses may override this method to answer its specific folder"
        | modelFolderName |
	modelFolderName := self name.
	(modelFolderName beginsWith: 'CM')
		ifTrue: [ modelFolderName := modelFolderName allButFirst: 2 ].
	(modelFolderName endsWith: 'Model')
		ifTrue: [ modelFolderName := modelFolderName allButLast: 5 ].
	^ modelFolderName
```

**Comment by hernanmd** [comment]
@tomooda the idea of the resource locator is to relief cormas model from responsibilities because now it has a lot of methods. And another value is to abstract a cormas model from named resource locations. 
So in the future we could have resources from remote locations (URL's) without folder names, in that case ResourceLocator can evolve separately from a cormas model.

**Comment by tomooda** [comment]
I see. Then, I think your solution is good enough for a tentative solution.

**Comment by pierbo** [comment]
I understand the goal of reducing the size of CormasModel. But if a user needs to know the simplified name of his model, he should have easy access to it (rather than looking for this information in the `CMEnvFileReader` class). So like Tomo, I will propose that CormasModel proposes (in a `conversion` protocol) an `asShortName` method that returns this.
Again, I know that we must avoid monster classes, but we must also simplify the search for useful operations for the users... not easy!

**Comment by hernanmd** [comment]
Ok @pierbo , actually this change doesn't remove any feature from CormasModel which coud be useful for a modeler. It only reduces the private sends sending very specific methods to CmEnvFileReader, so there is a cleaner protocol and it's easier to debug because methods are shorter.

Now this got me reviewing the parsing of .env files, but will push right after I got and .env file read into Pharo so you can review.
