### ISSUE TITLE
Rename CormasModel as CMModel

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#164]
In order to be prefix with CM like all classes, I propose to rename CormasModel to CMModel?

**Comment by tomooda** [comment]
How about CMAbstractModel?

**Comment by SergeStinckwich** [comment]
Yes meaningful, but maybe a bit long to wrote in the code for the modelers?

**Comment by pierbo** [comment]
Well, the modelers don't often call this class directly, but rather the class of their own model. So I vote in favor of CMAbstractModel.
