### ISSUE TITLE
accepteFonctionTailleEllipse contains a halt

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#176]
This method without sender and implementer contain a halt and I don't know  if it's still used

```Smalltalk
accepteFonctionTailleEllipse
	
	| controlr |
	self halt.
	controlr := (self builder componentAt: #fonction) widget controller.
	FonctionObs
		compile: controlr text
		classified: 'user functions'
		notifying: controlr
```

**Comment by SergeStinckwich** [comment]
and is written in French 👍

**Comment by SergeStinckwich** [comment]
Remove it if no sender/implementer.

**Comment by ElCep** [comment]
Done

**Comment by SergeStinckwich** [comment]
Done where? I don't see any PR? 😄

**Comment by ElCep** [comment]
Bad habit I don't do a lot of PR ... and I commit several things at the same time. ;-(

**Comment by SergeStinckwich** [comment]
ok no problem to group together many things if they related to the same issue, but close the issue, after it has been committed on the repository :-)
