### ISSUE TITLE
add: aPov contains halt 

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#180]
A lot of work to be done on POV (point of view). This add method aims to rewrite a point of view on an entity. The hierarchy is Object -> Model -> EntityPOV -> vectorialPOV -> VectorialCompositePOV
```
add: aPov
	self flag:#shouldBeRevised.
	self halt.
	self components add: aPov
```

**Comment by SergeStinckwich** [comment]
I think this is a method and class that is not used for the moment in the Pharo version. Do we want to use it?
