### ISSUE TITLE
Rehab Probes isses 

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#184]
Morning, everyone, 
@ChLePage and I have started porting Rehab under pharo. You'll find the code here: https://github.com/Rehab-game/Cormas-Model-Reha

We seem to have done the right thing with the superclass. We manage to open Rehab in the CORMAS interface (it works ! well done), but when initializing it there is an error: `shouldNotImplement : #add: should not been implemented in array`

So something wrong ! Any ideas what is different in probes management ?

**Comment by SergeStinckwich** [comment]
Can you be more precise on what code you execute that produce this error?

**Comment by ElCep** [comment]
Once you have cloned the rehab repository, in the pharo image, you can open the model with the nice UI. Once you choose the init condition, and the probes and you apply, it crashes.

**Comment by SergeStinckwich** [comment]
Rehab model running now without any problems even if the Cormas UI is broken.
