### ISSUE TITLE
what can we use in place of `self halt` in production

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#186]
In my archaeology of CORMAS, it seems to me that the `self halt` is used to allow the advancing user to debug his model.  e.g.
in ``CGStCormas class >> addNewClassType:InheritingFrom:``
```Smalltalk
selectionInList
		selection:
			(newList
				detect: [:s | (Cormas dropBlanksFromString: s) = aName]
				ifNone: [self halt]).
```

I understand the interest, but I have the impression that it's not great as a practice for basic users. Is there a flag or something that prevents our basic user from having a halt window jumping to his head?

**Comment by SergeStinckwich** [comment]
This is maybe the intention, but I think we should remove them as much as possible ... advanced users can still put breakpoints or halt if they need.

**Comment by ElCep** [comment]
So @SergeStinckwich considering my exemple for you it's better with 
```
selectionInList
		selection:
			(newList
				detect: [:s | (Cormas dropBlanksFromString: s) = aName]).
```

**Comment by SergeStinckwich** [comment]
I don't know what is doing this method first. Do we have a test to know the behavior of this method?

**Comment by ElCep** [comment]
nop ! no test !

**Comment by SergeStinckwich** [comment]
Replace by #196
