### ISSUE TITLE
IndexedSet should be replace by OrderedCollection

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#20]
Apparently Pharo OrderedCollection implement all IndexedSet methods.
We could safely replace IndexedSet class by OrderedCollection in Pharo.

**Comment by SergeStinckwich** [comment]
There is a commit to do that.
@nbecu could you have a look to:
Cormas-Core-SergeStinckwich.109, Cormas-Model-Conway-SergeStinckwich.7, Cormas-Model-Conway-SergeStinckwich.7 and Cormas-Model-ECEC-SergeStinckwich.12
and close the issue if everything is ok ?

**Comment by nbecu** [comment]
ok, indeed. all the indexedSet have been replaced by OrderedCollection in this new version.

but we will have the same issue each time we try to load a model from vw version, because they all use indexedsSet for collecting the instances of entities at the cormasModel level

**Comment by SergeStinckwich** [comment]
Yes, but I don't want to manage all the models legacy in the Pharo version at the moment.
We will provide a specific model loader that rewrite classes later if needed.

**Comment by nbecu** [comment]
well, if that is our choice , then we can remove all deprecated methods

2015-06-02 12:29 GMT+02:00 Serge Stinckwich <notifications@github.com>:

> Yes, but I don't want to manage all the models legacy in the Pharo version
> at the moment.
> We will provide a specific model loader that rewrite classes later if
> needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cormas/cormas/issues/20#issuecomment-107911031>.
>



-- 
__________________
Nicolas Becu
Chercheur au CNRS
Littoral Environnement et Sociétés (LIENSs) - UMR 7266
Bâtiment ILE
2, rue Olympe de Gouges
17 000 La Rochelle
Tel : 05 16 49 67 94
