### ISSUE TITLE
Why there is not a step: methods on each model ?

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#21]
There is a step: method in the ECEC model but not on FireAutomata and Conway models.
Should we add a step: methods for each models ?
Should we add an abstract step: method in CormasModel class ?

**Comment by nbecu** [comment]
indeed we should add an abstract step method in cormasModel.
given that, it is too the modeller to choose if he wants to call his method step, or with another name.
we don't want to force that.
in vw interface, when a model is opened and a simulation is initialized, an menu let the user choose which step method he want to launch

**Comment by SergeStinckwich** [comment]
Every step methods (that are at the moment inside the control protocol) should have a <control> pragma.

**Comment by pierbo** [comment]
we need to keep the possibility to have several step methods (ex: dailyStep, weeklyStep, monthlyStep...)
