### ISSUE TITLE
CMModelForTest is gone ? 

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#210]
From my side the `CMModelForTest` is gone and it broke a lot of test . has it been renamed  `CMAbstractModelTest` ? 
It seems that @tomooda modification from commit 1c1dd11 does something wrong :-)

**Comment by SergeStinckwich** [comment]
Which tests are broken? The CI says 126 green tests. Do you load the last version?

**Comment by ElCep** [comment]
I have tried on an other image ... my bad ! all green ! 
I will reload cormas from scrach
