### ISSUE TITLE
Probes stay empty in Rehab model

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#211]
Looking `Cormas-Model-Rehab` how it works properly again. There is an issue in the probes updates. I suspect it's link to what we work on issue #199 . in `CMReHabModel` >> `theBirds` doesn't find is class (as all other theXXXs). But I don't know how the probes are working.

**Comment by tomooda** [comment]
I made a PR to correct `familys` to `families` (https://github.com/cormas/cormas/pull/213).
To reproduce the problem of probes, I did `CMReHabModel initialize; probes` and got `#(#resourceBiomass #birdNewborns #harvest)` which I don't know details but looks making some sense.
To check `theBirds` methods, I also did `CMReHabModel new init; newEntity: CMReHabBird; theBirds` and got `an IndexedSet(a CMReHabBird)` which seems working.
Can you give a code that reproduce the problem?

**Comment by ElCep** [comment]
I don't know if it's link to [this](https://github.com/cormas/cormas/issues/199#issuecomment-661930876) modification. 

When I initialize Rehab with 
1. initialization`init`, 
2. Control : `run:`,
3. probes to record `Global>> harvest`

I have an error : 

```
errorSubscriptBounds: index 
	"Create an error notification that an improper integer was used as an index."
```
It seems coming from parkManager.

By the way initially Rehab was using `run:` method but there is `step:` method empty.

**Comment by ElCep** [comment]
I find the problem, I don't know how `init` was empty. So there were no agents, and that creates a problem.
