### ISSUE TITLE
methods in protocols starting by * are missing in pharo version

### ISSUE THREAD

**Issue by nbecu** [cormas/cormas#22]
I found that the method noOccupant of cormasModel was not present in the pharo version. 

actually in vw, this method is in a protocol named '* testing' and i found that all the methods of that protocol was missing in the pharo version.
perhaps all the methods in protocols starting by '*' were not copied. I didn't check but if this is the case we should correct it.

Originally, in vw version, methods stored in protocols strating by '*' are put here because they are the one made available for the end user - in a specific ui - to  interactt directly with the entities during the course of a simulation

**Comment by SergeStinckwich** [comment]
Ok I will check for the missing methods.
Protocols starting with '*XXX' in Pharo means methods from another package.
For example, you can add specific overrinding methods from a package to another.
I think we need to remove '*' from VW protocols in order to solve this issue.

This is a bad idea to rely on categories names ;-) We will have to switch on pragmas soon.

**Comment by SergeStinckwich** [comment]
Are you sure there is a CormasModel>>noOccupant. Could not find this method in the VW version. There is only a SpatialEntity>>noOccupant

**Comment by nbecu** [comment]
you are right. it is in spatialEntity and not in cormasModel. my mistake

as far as i remmember there are protocols with name starting by '*' in the
Entity class and subclasses, in cormasModel and in Cormas class (class side
if i'm not wrong)

I agree we should switch to pragmas. I continue this discusssion in another
thread.


2015-06-03 8:45 GMT+02:00 Serge Stinckwich <notifications@github.com>:

> Are you sure there is a CormasModel>>noOccupant. Could not find this
> method in the VW version. There is only a SpatialEntity>>noOccupant
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cormas/cormas/issues/22#issuecomment-108212728>.
>



-- 
__________________
Nicolas Becu
Chercheur au CNRS
Littoral Environnement et Sociétés (LIENSs) - UMR 7266
Bâtiment ILE
2, rue Olympe de Gouges
17 000 La Rochelle
Tel : 05 16 49 67 94

**Comment by SergeStinckwich** [comment]
I add missing methods from Entity Class and subclasses in Cormas-Core-SergeStinckwich.116
