### ISSUE TITLE
Second relaunch of a Rehab Model does not work 

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#229]
When you run Rehab once it now work like a charm. But if you what to change witch probe you are looking it doesn't work. 

```
errorSizeMismatch
	"Signal a SizeMismatch exception"

	SizeMismatch signal
```

I suspect it missing something cleaning in the init. Any ideas ?

**Comment by SergeStinckwich** [comment]
'''Smalltalk
setInitialBiomasses

	| initialPlantBiomasses |
	initialPlantBiomasses := #(1 1 2 1 1 2 0 2 3 2 1 3 1 2 1 1 3 1 0 2).
	self theZones
		with: initialPlantBiomasses
		do: [:z :i | z biomass: i]
```

Apparently ``self theZones`` and ``initialPlantBiomasses`` are collections with different sizes.

**Comment by ElCep** [comment]
Ok, but why it work in a first init ?

**Comment by SergeStinckwich** [comment]
I guess theZones are not reinitialized correctly at the second run.
