### ISSUE TITLE
How to manage CORMAS model's files ?

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#23]
For files like maps related to models, we have to find a way to manage them in the versioning system also.
This is not possible to version files in Monticello, but we can use git+Monticello together in order to put files on github for examples.
There was a thread on this recently on cormas-users mailing-list, raised by Nicolas Paget from IRSTEA.
One benefit of using github repositories for CORMAS models is that this easy for end-users to see diff between models and comment the models with the web interface.

**Comment by hernanmd** [comment]
Currently we are downloading a compressed resource file (zip or tgz) with all external files from GitHub.

I wrote a package to bootstrap resource download from Metacello config : https://github.com/hernanmd/MetacelloFileDownload

However I am open to other better alternatives.

**Comment by SergeStinckwich** [comment]
This is great Hernan ! 
Maybe you can move the model files in the CORMAS org, in a models repository ?

**Comment by tomooda** [comment]
Now we manage model files on the github repository via iceberg and GitBridge.
https://github.com/cormas/cormas/tree/master/assets
