### ISSUE TITLE
4 methods in `Obsolete` protocol in CMAbstractModel

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#237]
Can we just remove the 4 methods in obsolete protocol ? 
* `passiveClasses:`
* `socialClasses:`
* `spatialClasses:`
* `updateVS` --> I guest yes because all is commented here :-) 

A add a flag obsolete

**Comment by SergeStinckwich** [comment]
Yes, solve during the CORMAS sprint July 24th with @ElCep and @tomooda
