### ISSUE TITLE
CMAbstractModel >> createN: randomlyLocatedXXX: initMethod: arguments: constrainedBy: 3 almose same method

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#241]
I found 3 method in `CMAbstractModel` dedicated to different entities : 

* `createN: randomlyLocatedAloneAgents: initMethod: arguments:`
* `createN: randomlyLocatedAloneEntities: initMethod: arguments:`
* `createN: randomlyLocatedAloneObjects: initMethod: arguments:
`
2 questions : 

1. They seem to be doing almost the same thing. I think it should be possible to do one and the same method (with one test), and then methods for each type of entity that refers to this first method.  What do you think about this?
2. In the browser they are deprecated (I don't understand how! There is no flag). Any ideas ?

**Comment by SergeStinckwich** [comment]
Close by #254
