### ISSUE TITLE
Depencies on SmalltalkHub turn CI red

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#257]
We are still depending on some packages that are located in SmalltalkHub. Every time SmalltalkHub is down, your CI is red.
As SmalltalkHub will be deprecated soon, can we move the few packages that are located here?

@hernanmd apparently ProjectFramework depends on I18N who is located on SmalltalkHub, can you fix your baseline?

**Comment by tomooda** [comment]
ProjectFramework now refers to github repos of SState and I18N. closed.
