### ISSUE TITLE
What is the purpose of BBaseVisuel and AgentObs classes ?

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#27]
``BBaseVisuel`` is a subclass of ``Model``and ``AgentObs``is a subclass of ``BBaseVisuel``. There is no comment in ``BBaseVisuel`` and there is no reference to this class in CORMAS.
``AgentObs`` is also not commented but used in other classes.

```BBaseVisuel``` and ```AgentObs``` have a mix of english and French methods/instance variables.

**Comment by olekscode** [comment]
Both classes have been removed
