### ISSUE TITLE
Error raised when creating a first model with the CORMAS interface

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#271]
Creating a first model after the CORMAS interface is launched, raise a the following error: receiver of "cormasModelName" is nil. Please choose another name. This error does not appears anymore the second time.

With spend sometimes with @tomooda to understand the problem. This is apparently linked to the way the FSM of the project is managed. Any hints @hernanmd ?

**Comment by hernanmd** [comment]
In #274
