### ISSUE TITLE
MetacelloConflictingProjectError with BaselineOfGeometry

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#273]
Loading in Pharo 8 (64-bit) with the expression in the README causes a conflict with BaselineOfGeometry fetched from two different repositories

`MetacelloConflictingProjectError: Load Conflict between existing BaselineOfGeometry [baseline] from github://peteruhnak/geometry/repository and BaselineOfGeometry [baseline] from github://pharo-contributions/Geometry/src`

For now we could use onConflictUseIncoming, but we should locate where the peteruhnak dependency is coming from, and try to use the pharo-contributions one.

**Comment by hernanmd** [comment]
This is caused because we're loading Roassal2 and Roassal3 as commented in #116 which also makes [CI to fail](https://travis-ci.org/github/cormas/cormas/builds/722179209?utm_source=github_status&utm_medium=notification)

**Comment by SergeStinckwich** [comment]
Yes the idea was to have Roassal2 and 3 in the same image during the transition. I start to do an experiment with R3 on ECEC model.

**Comment by SergeStinckwich** [comment]
This is only one example in ECEC that use R3, the other one still use R2. I will remove R3 from Baseline for the moment.

**Comment by SergeStinckwich** [comment]
For the moment I remove R3 from the baseline. An improvement would be to have 2 groups for R2 and R3
