### ISSUE TITLE
PMFishmanMooreRandomGenerator error

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#282]
The Cormas randomGenerator seems to have changed ? Something link with an other package ? 

`PMFishmanMooreRandomGenerator is missing`

```Smalltalk
randomGenerator
	^ randomGenerator ifNil: [ randomGenerator := PMFishmanMooreRandomGenerator new ] 
```

**Comment by ElCep** [comment]
@serge PM is it for PolyMath ?

**Comment by tomooda** [comment]
@ElCep you need to update the PolyMath package.

**Comment by SergeStinckwich** [comment]
Yes maybe you have a old version of CORMAS, you need to reload it in a fresh image to have all the correct dependencies
