### ISSUE TITLE
Ressource locator does not work

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#284]
For example, if you try to initialize with the CORMAS UI, a ``CMDiffuseModel``, you have an error because resourceLocator is nil.

**Comment by hernanmd** [comment]
The .env file for Diffuse model which is 40x40.env seems incomplete (doesn't have attributes) :

```
dimensions	40 40
cloture	closed
connexite	four
delimiteur	1
attributs
```

Is this file correct @pierbo or @ElCep ?

And a related question: can attributs be incomplete or without values?

I also checked against the VW 7.6 version, the .env file is the same, additionally a DNU raised:

![Captura de pantalla 2020-09-25 a la(s) 23 24 59](https://user-images.githubusercontent.com/4825959/94328199-dd328e80-ff86-11ea-9b31-f772482de2de.png)
