### ISSUE TITLE
How to compare two models?

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#286]
To provide more reliable tests, we should define when two Cormas models (each currently defined as subclass of CMAbstractModel(s)) are equal. In the current implementation, a cormas model includes several instance variables: "cormas" timeStep channel activeInit activeControl spaceModel data .... etc.

Maybe @pierbo , or @ElCep can help here?

**Comment by SergeStinckwich** [comment]
It does make too much sense for me to compare models.

**Comment by pierbo** [comment]
Well, because it is important to keep the availability for a modeler to use class variables, we decided (for the moment) to run 1 model in 1 image. So, to compare 2 different versions of a model, we must open 2 images.
In one image, we can open 2 instances of Cormas with 2 different models, but in that case we can only run 1 simulation, because "cormas", "timeStep"etc will be shared.

**Comment by SergeStinckwich** [comment]
This is now possible to run two or more models in the image since @tomooda made some modifications.

**Comment by hernanmd** [comment]
My apologies because I wasn't clear enough. What I meant is which attributes should be considered when implementing the equal (#=) method. I see two cases:

- Two models has the same name, but they could have for example different space models. Are they considered different (#= answer false) or the same (#= answers true)?
- Two models has different name but the same "essential" attributes. These attributes needs to be defined IMO. As @pierbo said, the **timeStep** is a shared attribute, so it wouldn't be essential to (compare) a model. But also there are the probes represented by the instance variable "**data**". There is the "**activeInit**" which is a Symbol representing a selector to use when initializing a simulation.

**Comment by SergeStinckwich** [comment]
This is not comparable at all. They might have different names, spaces, agents, ... how could you find ways to compare them?

**Comment by hernanmd** [comment]
I'm closing this issue because we don't have a real case for this now besides possible use cases for implementing tests.
