### ISSUE TITLE
Multi probes selection

### ISSUE THREAD

**Issue by pierbo** [cormas/cormas#291]
When initializing a model, we cannot select several probes at the same time. It should work using shift-click or Ctrl-click on probes. In the following UI, we should able select both dead and alive probes

![Screenshot 2020-12-04 at 19 20 19](https://user-images.githubusercontent.com/327334/101157886-ca62c700-3665-11eb-9ed2-e55f9c775fc1.png)

**Comment by SergeStinckwich** [comment]
![Uploading Screenshot 2020-12-04 at 19.18.56.png…]()
