### ISSUE TITLE
Create a Cormas instance diagram

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#303]
To have a better understanding between relationships of Cormas application objects, create an editable diagram with the most important objects and their how they interact (including selectors).

**Comment by hernanmd** [comment]
![CORMAS Instance Diagram](https://user-images.githubusercontent.com/4825959/94703182-f3d53e80-0314-11eb-986d-1bce2f6b380d.png)

**Comment by SergeStinckwich** [comment]
To be moved to the Wiki.
