### ISSUE TITLE
Replace assets.zip by files on github

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#323]
Models assets are available as a zip file: assets.zip but this is not really convenient when you want to modify the model asset. One idea is to put all the model files in github repository. Maybe by using GitBridge: https://github.com/jecisc/GitBridge

**Comment by tomooda** [comment]
We can now use the local git repository via iceberg.
https://github.com/cormas/cormas/pull/335
https://github.com/cormas/cormas/pull/336
We need to remove the code that downloads and unzips the assets.zip file, and then remove the zip file from the repository.

**Comment by tomooda** [comment]
removed download script for assets.zip from the baseline.
https://github.com/cormas/cormas/pull/339
