### ISSUE TITLE
Documentation needed for .cells

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#332]
.cells files replace .env files. There was some documentation for .env file: https://github.com/cormas/cormas/wiki/External-files but we don't documentation how to use .cells.

**Comment by tomooda** [comment]
Also add description of ASC file. cf https://github.com/cormas/cormas/issues/135

**Comment by tomooda** [comment]
Now on https://github.com/cormas/cormas/wiki/Cells:-directory-with-environment-definition-files .
