### ISSUE TITLE
Massive VW dead code cleanup

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#348]
Code cleanup to remove old or unused VW classes

**Comment by hernanmd** [comment]
Dead code to be considered anything which is strongly dependent of VW, for example, subclasses of UIApplicationModel, references to VW UI classes like List or MultiSelectionInList, methods answering Arrays as resources like menus, bitmaps, etc. 

The strategy applied was to look for class references of a suspected class which seems to be related with VW/UIPainter code. Then remove iteratively methods which contain references to this class. If a method contains senders, analyse its usage again by listing their senders, and remove it. And so on.
The same principle was applied to VW UI methods, like the ones using ValueHolders.

In many cases UI code in UIApplicationModel subclasses was mixed with Cormas logic code. Extracting this code one by one is a time-consuming task, with no clear outcome.

- UIApplicationModel class and subclasses were removed, including references
- Removed HotDraw classes.
- Much of the Cormas convenience methods also were cleaned.
- Figure classes were removed (to be replaced by OpenPonk).

**Comment by SergeStinckwich** [comment]
Youpi !!!
