### ISSUE TITLE
"This model does not define...."

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#350]
When I create a model with the UI, from scratch, and click the Simulate button (upper leftmost red) to open the "Confirmation before launching" window, two warning dialogs appear:

- The model does not define any method for initialization!
- The model does not define any method for control!

Instead of just informing the user. Could we be more proactive and ask something like

- "Do you want to define an initialization method?"
- "Do you want to define a control method?"

And then open a System browser?

Furthermore, I don't see any sense opening the "Confirmation before launching" window without control or initialization methods.

What do you think?

**Comment by pierbo** [comment]
I am agree !
