### ISSUE TITLE
allClassesInPackage or allClasses

### ISSUE THREAD

**Issue by pierbo** [cormas/cormas#36]
to go on cleaning, there are 2 similar class methods: allClassesInPackage or allClasses.
`#allClasses` is expected to return the list of the subclasses of Entity that belong to the model.
Perhaps we should rename it as `#allEntityClasses`?

```Smalltalk
allEntityClasses
	"return all the classes of the model (except the classes that inheriting from Msg and other classes like Interface etc"

	| collection |
	collection := self allClassesInPackage.
	collection removeAllSuchThat: [:cl | (cl inheritsFrom: CMEntity) not].
	^ collection
```

**Comment by SergeStinckwich** [comment]
```allClassesInPackage``` what something I add, I don't remember why :-)

Can you wrote a test first, to specify what is the expected behavior ?

**Comment by pierbo** [comment]
Yes, we found that when loading a ST file containing a Package (for ex. 
Cormas-Model-ECEC-PE  (PE for PierreEtienne !!) ), Pharo considers it as 
a sub package of 'Cormas-Model-ECEC' and adds a tag 'PE' :

So we changed the |allClassesInPackage| in order to get only the correct 
tagged classes.


Le 25/04/2018 à 02:32, Serge Stinckwich a écrit :
