### ISSUE TITLE
A better printOn: for a model

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#372]
There is no customized ``#printOn:`` even for an abstract model. This is not useful for debugging.

Any of the following instance variables of a model could be summarized (currently) so we could have a quick view of a model without walking down the inspectors:

timeStep
channel 
activeInit 
activeControl 
spaceModel 
data 
simManager 
projectManager 
database 
collector 
defaultAttributesSetter 
sensitivitySetter 
delayedChanges 
initStatus

**Comment by SergeStinckwich** [comment]
Definitively agree with that. The same for CMAgent, CMGroup, etc ...

**Comment by SergeStinckwich** [comment]
What would be even better for modelers is to have some specific gtview but GToolkit support will be deprecated in Pharo 9 unfortunately.
