### ISSUE TITLE
Integrate model repository setup as part of installation

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#389]
After installing all the CORMAS packages and dependencies through the Baseline, create a directory tree under the user HOME which serves as the base location for CORMAS files, and place the exported models as project files in a demos directory. The demos directory is the default search location for the Open project dialog.

For example
```
/User/<username>/CORMAS
/User/<username>/CORMAS/demos
/User/<username>/CORMAS/preferences
...
```

**Comment by tomooda** [comment]
How do we integrate this with the existing assets/models/ directory?
