### ISSUE TITLE
Task: Integration of GIS in Cormas core

### ISSUE THREAD

**Issue by nbecu** [cormas/cormas#41]
Nick+Nico: integration of GIS (Geranium project -- Pharo functionality ++  Continuous or Large-Grid Space) in Cormas core

    4.1 Does that need ESRI support?? http://smalltalkhub.com/#!/~hernan/Shapes
    4.2  Etienne, Nico and who ever wants, want to work on a study case for GIS integration in the cormas core, which would be a fire diffusion model on top of a vectorial representation of a territory that can be downloaded from openStreetMap

**Comment by ElCep** [comment]
@npapoylias some news about this point?

**Comment by SergeStinckwich** [comment]
I will close this issue, because nothing happens. Regarding GIS, we are working right now on #135
