### ISSUE TITLE
Error when the space is open

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#444]
Open ConwayModel, then initialize model with initRandomly, Global>>alive, stepSynchronously:
Open space, generate the error: ``Instance of RSBox did not understand #computeEncompassingRectangleFor:matrix``.
Linked to: https://github.com/ObjectProfile/Roassal3/issues/408

**Comment by SergeStinckwich** [comment]
This can be solved apparently by loading the full roassal3 by hand after loading CORMAS.

**Comment by hernanmd** [comment]
Included a workaround in the last PR
