### ISSUE TITLE
Remove XMLModel class?

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#450]
It seems XML representation of models is not used anymore in this version, or will not be used.

Check if we want to keep supporting this format.

**Comment by SergeStinckwich** [comment]
I agree with this. This is still possible to use another to serialize model in Pharo if needed.

**Comment by pierbo** [comment]
Yes, this is not used anymore (even for the VW version).

**Comment by SergeStinckwich** [comment]
Not to be closed, before the code is removed from the repository ;-)
