### ISSUE TITLE
Space Model refactorization

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#465]
SpaceModel seems too complex and can be refactored.

- Add a class comment explaining the role of the spatialEntities Dictionary and the differences with elementaryEntities Dictionary since these two attributes are important given the amount of senders they have.
- gridCellShape could be 
  - #squared
  - #hexagonal
  - #irregular (not used?)
  - another possible value?
  - Explore the possible combinations with #nbNeighbours so we can avoid multiple if's.
- Review if it is mandatory being a subclass of Model.
- #arrayOrigins: has no senders.
- Review if Neighbours behavior could be composed into another specialized object.
- The following methods can be deleted or move it into another package/class since it has no senders.
  - #saveAttributesMIFMID:fileParameters:class: 
  - exportToMapInfo:inFile:
  - setUncompleteGridFromData:forAttributes:
  - saveNeighboorsClass:separator:
  - loadNeighboorsClass:separator: (only used by DemoAggregates?)
 - Methods in protocol 'landscape indices' delegates much of their behavior into cormasModel, evaluate if this should be moved.

**Comment by pierbo** [comment]
- I think spatialEntities Dictionary is enough. The #elementaryEntities could be a method returning the cells' collection from this dictionary.
- gridCellShape could be
#squared (with 4 or 8 neighbors)
#hexagonal
#irregular (not used?) Yes, for the vectorial maps
another possible value? = 3
- #arrayOrigins: has no senders. So it can be removed
-  (don't know)
- Yes, the very specific methods to save and load (#saveAttributesMIFMID, etc) should be removed
