### ISSUE TITLE
Task: Organize CORMAS models in a github repository

### ISSUE THREAD

**Issue by nbecu** [cormas/cormas#49]
Serge: Organize CORMAS models in a github repository (Cormas-Models group in git + Project per Repo=Repo-Url as Project Identifier)

**Comment by ElCep** [comment]
We can close it non ?

**Comment by nbecu** [comment]
well, I'm not sure this issue is resolved, because as far as I understood,
for the moment when we push commits to the Cormas repository, we push all
together  the Cormas-core and UI as well as the Cormas Models (ECEC,
Conway...).
This is not so convenient, because developers as well as users, need to
differentiate between the Cormas engine and the models
For instance, I may want to pull the changes Bruno made to the Cormas
engine, without pulling his version of the Cormas models




Le ven. 1 févr. 2019 à 09:42, Etienne DELAY <notifications@github.com> a
écrit :

**Comment by ElCep** [comment]
Sorry, it was not clear for me!

**Comment by hernanmd** [comment]
I don't know the status of this issue. Should each model have its own github repository?

I think that's what the "Load from URL" feature should do.

**Comment by ElCep** [comment]
I think it's cleaner to have a repository for each model indeed... 
'load from url' really do the job? If yes it's enough from my point of view.

**Comment by hernanmd** [comment]
@ElCep Actually it needs to be done :) however I wanted to reach consensus before jumping to code

**Comment by ElCep** [comment]
I think we have consensus :-)

**Comment by SergeStinckwich** [comment]
Right now, all the models are part of the core code. This simplify the development process. We will revise this later if there is too much models.
