### ISSUE TITLE
Use conventions for standard methods

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#513]
We could use conventions for selectors of commonly implemented methods for some models:

For initialization:

- initSpace
- noAgent (to load a space without agents)
- initAgents (to create and randomly position agents of all subclasses of an Agent class implemented by the user)
- initAgents: aClassOrCollection (to create and randomly position agents of a specified superclass or a collection of classes specified by the user)

For most agents:

- die

For moving:

- step
- move

For agents with reproductive behaviors:

- findPartner
- partner
- reproduce
- age

For agents with biomass:

- eat
- consumeEnergy

**Comment by pierbo** [comment]
I am not sure that those conventions are necessary. It is up to the modeler to specify the `initialization` and `step` methods he wants for his model. Moreover, this can be specified directly from his UML diagram.
Moreover, any method that involves randomness should explicitly specify in its title that there is randomness.
