### ISSUE TITLE
CMSpatialEntity deserves better Pharo-style deprecations

### ISSUE THREAD

**Issue by olekscode** [cormas/cormas#543]
The following methods of `CMSpatialEntity` class are deprecated with a method comment:

- `distCenter:`
- `myOccupantAt:`
- `myOccupants:`
- `peripherieRayon:`

In Pharo, we have a better way of deprecating methods:

```st
self deprecated: 'Explain why'.
```
And we can also use transformation rules:
```st
self
    deprecated: 'Explain why'
    transformWith: '`@rec oldSelector' -> '`@rec newSelector'.
```

**Comment by SergeStinckwich** [comment]
Thank you for your comment Oleks. There is a great accumulation of legacy code in CORMAS and a lot of work should be done to understand what is used or not.
