### ISSUE TITLE
Rename #numLine and #numCol to #rowIndex and #columnIndex

### ISSUE THREAD

**Issue by olekscode** [cormas/cormas#548]
Those method names are not very good:
```st
CMSpatialEntityElement >> numCol
	"Purpose: returns the X coordinate of the cell in a regular spatial grid"
	^self id - ((self numLine - 1) * self spaceModel column)
```
```st
CMSpatialEntityElement >> numLine
	"Purpose: returns the Y coordinate of the cell in a regular spatial grid"
	^(self id / self spaceModel column) ceiling
```
I propose to rename them to `columnIndex` and `rowIndex`

We can try to be consistent with `PMMatrix` and `SequenceableCollection` on this one:
PMMatrix has rows and columns
SequenceableCollection has `indexOf: anElement` method

**Comment by hernanmd** [comment]
I agree, but check because models rely on those methods so it could be nice to do a migration tasks.
