### ISSUE TITLE
Baseline: Error when loading Magritte

### ISSUE THREAD

**Issue by olekscode** [cormas/cormas#549]
Cormas fails to load on Pharo 10 and 11 (perhaps also earlier versions) because the baseline of Magritte raises the following exception:

```
MetacelloNameNotDefinedError: project group, or package named: 'Magritte-Tests-Pharo-Model' not found when used in requires: or includes: field of package: 'Magritte-Tests-Model' for version: baseline of BaselineOfMagritte.
```

**Comment by olekscode** [comment]
It goes like this:

1. On Pharo 9, 10, Cormas loads [hernanmd/class-editor](https://github.com/hernanmd/class-editor) - the fork of [OpenPonk/class-editor](https://github.com/OpenPonk/class-editor)
2. [hernanmd/class-editor](https://github.com/hernanmd/class-editor) loads [hernanmd/openponk](https://github.com/hernanmd/openponk) - the fork of [OpenPonk/openponk](https://github.com/OpenPonk/openponk)
3. [hernanmd/openponk](https://github.com/hernanmd/openponk) loads Magritte at specific commit [49781e985875315d06c5991f094c30d6f8c9f02d](https://github.com/magritte-metamodel/magritte/commit/49781e985875315d06c5991f094c30d6f8c9f02d)
4. That commit seems to have a bug in the baseline.

**Solution A:** (if possible) use [OpenPonk/class-editor](https://github.com/OpenPonk/class-editor) instead of [hernanmd/class-editor](https://github.com/hernanmd/class-editor) because official disctribution is easier to maintain

**Solution B:** Update [hernanmd/openponk](https://github.com/hernanmd/openponk) to load Magritte at the latest version. Or at least the version that doesn't break

**Comment by hernanmd** [comment]
I would go for **Solution B**, as OpenPonk/class-editor could have significant changess since forked, from both sides.

**Comment by olekscode** [comment]
Fixed this issue with https://github.com/hernanmd/openponk/pull/1
