### ISSUE TITLE
Write a BaselineOfCormas class

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#61]
BaselineOf class is much simpler to maintain than ConfigurationOf, and it is more supported by now in current Pharo development efforts.

The BaselineOf should work with the following install expression:

```smalltalk
Metacello new
  baseline: 'Cormas';
  repository: 'github://Cormas/cormas/repository';
  load.
```

If groups and/or versions are defined/maintained, they should be supported:

```smalltalk
Metacello new
  baseline: 'Cormas';
  repository: 'github://Cormas/cormas/repository';
    version: #stable;
    load: 'Group'.
```

**Comment by SergeStinckwich** [comment]
👍 Yes we need a BaselineOf in order to load everything from the github repository more easily.
