### ISSUE TITLE
Documentation issue:  Link to stable version is broken

### ISSUE THREAD

**Issue by cbradyatinquire** [cormas/cormas#671]
Hello - the link to the stable version of CORMAS seems to be broken.  Does anyone know where to download this version?

>>
Current stable version of CORMAS is based on VisualWorks 7.6 and still can be found on: http://cormas.cirad.fr/indexeng.htm 
>>

**Comment by olekscode** [comment]
Hello @cbradyatinquire 

Did you follow the installation instructions here?
https://github.com/cormas/cormas#standard-installation
