### ISSUE TITLE
readCsvFile in Cormas doesn't work

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#68]
Do something ... use dataframe package or debug the method but do something !

**Comment by SergeStinckwich** [comment]
Ahah yes !!!
read CSV to do what ?

**Comment by ElCep** [comment]
:-) Read a CSV is not enough !

**Comment by ElCep** [comment]
Done readCSV and readMatrix are fixed using NeaoCSV ... I don't know if this package is in the base line ? By the way some depences are still broken (`readCsvMap:`, `readCsvFile:`, `readCsv:`)

**Comment by ElCep** [comment]
@hernanmd , I don't know if you have added NeoCSV in the BaslineOfCormas but I had taken some methods and especially I had tagged as #depreciated: `readCsv`, `readCsv: myModel:` . In the same time, I had proposed a new method tagged  #shouldBeRevised : `readMatrix:sep: `. 
Today it doesn't work so I don't know if NeoCSV package is still in the Baseline.

**Comment by hernanmd** [comment]
Hi Etienne

NeoCSV should be loaded by the current BaselineOf:
https://github.com/cormas/cormas/blob/master/repository/BaselineOfCormas/BaselineOfCormas.class.st
I will check it later tonight.
Cheers,

Hernán
