### ISSUE TITLE
Pluralization: Common issue when pluralizing specific words

### ISSUE THREAD

**Issue by Cracen26** [cormas/cormas#732]
When creating an instance variable in the model related to a specific agent, the pluralization module of Cormas is unable to pluralize certain words.
The following example shows us a case of design flaw; the plural of 'human/Human' is supposed to be 'humans/Humans,' however, 'asPlural' returns 'humans/Humen.

'human' asPlural . "'humans'"
'Human' asPlural . "'Humen'"

**Comment by olekscode** [comment]
Fixed by #734
