### ISSUE TITLE
Port to Pharo 7.0

### ISSUE THREAD

**Issue by hernanmd** [cormas/cormas#76]
With the new release of Pharo 7 several classes were deprecated and [coding idioms have changed](https://github.com/pharo-open-documentation/pharo-wiki/blob/master/Migration/MigrationToPharo7.md). An update of multiple underlying packages required by CORMAS is necessary to stay updated.

**Comment by hernanmd** [comment]
Loading OpenPonk in Pharo 7 produces the following error:

> MetacelloConflictingProjectError: Load Conflict between existing BaselineOfFileDialog [baseline] from github://peteruhnak/file-dialog:v1.x/repository and BaselineOfFileDialog [baseline] from github://peteruhnak/file-dialog/repository

Until the [PR](https://github.com/OpenPonk/openponk/pull/4) is accepted in the main OpenPonk repository, I propose to load fixes from https://github.com/hernanmd/openponk

**Comment by JanBliznicenko** [comment]
I am working on updating, fixing and improving OpenPonk for our cases, including fixes for Pharo 7.
Current master of OpenPonk is usable enough on Pharo 7 and 8. After I finish few fixes and planned improvements and check once (or like 10 times) again everything works as it should, I will make another tag/release, probably named 2.0.0 (yes, I know, it should be more like 0.0.2 :) but the major version increase is there to make sure no 1.x dependencies would load this version which do not work on Pharo 6 anymore)

**Comment by SergeStinckwich** [comment]
Thank you Jan for your commitment. I think we should move Cormas to Pharo 8.0 now.
This is great if  you have a working version of OpenPonk for Pharo 7/8 now. Which version we should load from CORMAS baseline ?

**Comment by JanBliznicenko** [comment]
For now, for development purposes, just use master branch. In few weeks, I will do a release 2.0.0

**Comment by SergeStinckwich** [comment]
We move the development to Pharo 8.0 now.
