### ISSUE TITLE
icons missing in the Simulation window interface 

### ISSUE THREAD

**Issue by nbecu** [cormas/cormas#91]
4 icons are missing in the sim interface (in Pharo 7.0.3 version)
- next step
- run
- replay 1 stored step
- replay stored simulation
![image](https://user-images.githubusercontent.com/7630183/56458133-196dc280-6383-11e9-8730-e7e71cdc45ee.png)

**Comment by SergeStinckwich** [comment]
I guess this is related to #78

**Comment by hernanmd** [comment]
I just did a commit which solves this issue to my repository https://github.com/hernanmd/cormas/commit/d9a5b7599c263e78d9b7dee7359e64d098a8067d

I guess I should wait for #94 to be integrated before I sent a PR for this one?

**Comment by hernanmd** [comment]
Merged in #95
